import { code128Bars } from './labels';

/**
 * THE PRINTED SHEET OF WAYBILLS, AS A STRING.
 *
 * Pure, so it can be measured. The print route used to build this inline,
 * which meant the only way to know how heavy two hundred labels were was to
 * print two hundred labels — and the answer, it turned out, was "heavy
 * enough to freeze the tab".
 *
 * The page it produces is standalone: it is NOT the application with the
 * rest hidden. There is no dashboard, no sidebar and no script bundle to
 * hide, so `visibility: hidden` tricks would change nothing. What made it
 * slow was what it contained, and that is what changed here.
 */

export interface LabelView {
  courier: string;
  ref: string;
  courierCode: string;
  name: string;
  phone: string;
  place: string;
  items: string[];
  cod: string;
  /** Pre-rendered QR svg. Generated by the caller because the library is async. */
  qrSvg: string;
}

export interface SheetSize {
  /** Label size in millimetres. */
  width: number;
  height: number;
  /** Paper size; omitted means the paper IS the label (a thermal roll). */
  sheetWidth?: number;
  sheetHeight?: number;
}

/**
 * Labels per print run when the batch is large.
 *
 * Above this the sheet does not open the print dialog on its own: it shows
 * the ranges and lets the operator print them one at a time. A print
 * preview of two hundred pages is rasterised in one blocking pass, and on
 * a warehouse PC with a thermal driver that is what froze the tab. Fifty is
 * a run a thermal printer finishes before anybody wonders whether it hung.
 */
export const PRINT_CHUNK = 50;

export function esc(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
}

/**
 * A Code 128 barcode as ONE svg path.
 *
 * It used to be one `<rect>` per dark bar — about fifty per label, so about
 * ten thousand elements for a run of two hundred, every one of which the
 * print preview has to lay out and rasterise on every page. A single path
 * with one sub-path per bar draws exactly the same pixels from one element.
 *
 * `crispEdges` keeps the bars from being anti-aliased into grey, which a
 * courier's scanner reads as a different width.
 */
export function barcodeSvg(value: string, widthMm: number, heightMm: number): string {
  const bars = code128Bars(value);
  const total = bars.reduce((a, b) => a + b, 0);
  let x = 0;
  let dark = true;
  let d = '';
  for (const w of bars) {
    if (dark) d += `M${x} 0h${w}v10h-${w}z`;
    x += w;
    dark = !dark;
  }
  return (
    `<svg viewBox="0 0 ${total} 10" preserveAspectRatio="none" width="${widthMm}mm" height="${heightMm}mm" ` +
    `shape-rendering="crispEdges"><path d="${d}" fill="#000"/></svg>`
  );
}

function labelHtml(l: LabelView, size: SheetSize): string {
  return `<section class="label">
  <div class="head"><strong>${esc(l.courier)}</strong><span dir="ltr">${esc(l.ref)}</span></div>
  <div class="who">
    <p class="name">${esc(l.name)}</p>
    <p dir="ltr">${esc(l.phone)}</p>
    <p>${esc(l.place)}</p>
  </div>
  <ul class="items">${l.items.map((i) => `<li>${esc(i)}</li>`).join('')}</ul>
  <div class="cod"><span>المبلغ عند الاستلام</span><strong dir="ltr">${esc(l.cod)}</strong></div>
  <div class="codes">
    <figure class="barcode">${barcodeSvg(l.courierCode, size.width - 32, 14)}<figcaption dir="ltr">${esc(l.courierCode)}</figcaption></figure>
    <figure class="qr">${l.qrSvg}<figcaption dir="ltr">${esc(l.ref)}</figcaption></figure>
  </div>
</section>`;
}

/** How many labels one sheet holds. A sheet that fits none still gets one per page rather than clipping it. */
export function labelsPerPage(size: SheetSize): number {
  const pageW = size.sheetWidth ?? size.width;
  const pageH = size.sheetHeight ?? size.height;
  const across = Math.max(1, Math.floor(pageW / size.width));
  const down = Math.max(1, Math.floor(pageH / size.height));
  return Math.max(1, across * down);
}

export function renderLabelSheet(labels: LabelView[], size: SheetSize): string {
  const pageW = size.sheetWidth ?? size.width;
  const pageH = size.sheetHeight ?? size.height;
  const perPage = labelsPerPage(size);
  const pages = Math.ceil(labels.length / perPage);

  // One wrapper per PAGE, laid out as a grid of fixed cells. The labels used
  // to be one long flex-wrap run across the whole body, which the print
  // engine had to paginate by measuring every item; a page that is already
  // a page needs no measuring.
  const sheets: string[] = [];
  for (let p = 0; p < pages; p++) {
    const chunk = labels.slice(p * perPage, (p + 1) * perPage);
    // Which print run this page belongs to, by the index of its first label.
    const run = Math.floor((p * perPage) / PRINT_CHUNK);
    sheets.push(`<div class="page" data-run="${run}">${chunk.map((l) => labelHtml(l, size)).join('')}</div>`);
  }

  const runs = Math.ceil(labels.length / PRINT_CHUNK);
  const chunked = runs > 1;

  // One rule per run: while a run is being printed, every page outside it is
  // display:none — and a page that is not displayed is not laid out or
  // rasterised, which is the whole saving.
  const runRules = chunked
    ? Array.from({ length: runs }, (_, r) =>
        `body[data-run="${r}"] .page:not([data-run="${r}"]) { display: none; }`
      ).join(' ')
    : '';

  const runButtons = chunked
    ? Array.from({ length: runs }, (_, r) => {
        const from = r * PRINT_CHUNK + 1;
        const to = Math.min((r + 1) * PRINT_CHUNK, labels.length);
        return `<button type="button" class="run" data-print-run="${r}">${from}–${to}</button>`;
      }).join('')
    : '';

  return `<!DOCTYPE html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>بوالص الشحن — ${labels.length}</title>
<style>
  @page { size: ${pageW}mm ${pageH}mm; margin: 0; }
  * { box-sizing: border-box; }
  html, body { margin: 0; background: #eef2f6; }
  body { font-family: Tahoma, Arial, sans-serif; color: #121926; }

  /* The toolbar exists on screen and nowhere else. */
  .bar { position: sticky; top: 0; z-index: 1; display: flex; align-items: center; gap: 12px;
         padding: 10px 16px; background: #121926; color: #fff; font-size: 14px; }
  .bar button { margin-inline-start: auto; font: inherit; font-weight: bold; padding: 8px 18px;
                border: 0; border-radius: 8px; background: #fff; color: #121926; cursor: pointer; }
  .bar .muted { opacity: .7; font-size: 12px; }
  .bar .run { margin: 0; padding: 6px 12px; background: #364152; color: #fff; font-weight: normal; }
  .bar .run.done { background: #00994d; }
  .bar .runs { display: flex; gap: 6px; flex-wrap: wrap; }

  .page { width: ${pageW}mm; height: ${pageH}mm; margin: 8px auto; background: #fff;
          display: grid; grid-template-columns: repeat(auto-fill, ${size.width}mm);
          grid-auto-rows: ${size.height}mm; align-content: start; overflow: hidden;
          /* Each page is its own layout island: changing one never makes the
             browser re-lay out the other hundred and ninety-nine. */
          contain: layout paint; }
  .label { width: ${size.width}mm; height: ${size.height}mm; padding: 4mm; overflow: hidden;
           display: flex; flex-direction: column; gap: 2mm; border: 1px dashed #ccc; }
  .head { display: flex; justify-content: space-between; align-items: center; font-size: 10pt; border-bottom: 1px solid #000; padding-bottom: 1mm; }
  .who .name { font-size: 12pt; font-weight: bold; margin: 0 0 1mm; }
  .who p { margin: 0; font-size: 9pt; }
  .items { margin: 0; padding: 0 4mm 0 0; font-size: 8pt; }
  .cod { margin-top: auto; display: flex; justify-content: space-between; font-size: 11pt; border-top: 1px solid #000; padding-top: 1mm; }
  .codes { display: flex; gap: 2mm; align-items: flex-end; justify-content: space-between; }
  .codes .barcode { flex: 1; }
  figure { margin: 0; text-align: center; }
  figcaption { font-size: 7pt; letter-spacing: 1px; }

  @media print {
    ${runRules}
    html, body { background: #fff; }
    .bar { display: none; }
    .page { margin: 0; break-after: page; }
    .page:last-child { break-after: auto; }
    .label { border-color: transparent; }
  }
</style></head>
<body>
<div class="bar">
  <strong>${labels.length} بوليصة</strong>
  <span class="muted">${pages} ${pages === 1 ? 'صفحة' : 'صفحات'}</span>
  ${chunked ? `<span class="muted">اطبعها على دفعات:</span><span class="runs">${runButtons}</span>` : ''}
  <button type="button" data-print-run="all">${chunked ? 'اطبع الكل' : 'اطبع'}</button>
</div>
${sheets.join('\n')}
<script>
  (function () {
    var body = document.body;
    function printRun(run, button) {
      if (run === 'all') body.removeAttribute('data-run'); else body.setAttribute('data-run', run);
      window.print();
      // Marked once it has gone to the printer, so an operator working
      // through four runs can see which ones are done.
      if (button && run !== 'all') button.classList.add('done');
    }
    window.addEventListener('afterprint', function () { body.removeAttribute('data-run'); });
    document.querySelectorAll('[data-print-run]').forEach(function (b) {
      b.addEventListener('click', function () { printRun(b.getAttribute('data-print-run'), b); });
    });

    // A small batch opens the print dialog by itself, as it always did — but
    // only once the page has been laid out. Calling print() from onload fired
    // it before layout settled, so the preview laid out and rasterised every
    // page in one blocking pass. A large batch waits for the operator to pick
    // a run: opening two hundred pages at once is exactly what froze.
    ${chunked ? '' : "window.addEventListener('load', function () { requestAnimationFrame(function () { requestAnimationFrame(function () { window.print(); }); }); });"}
  })();
</script>
</body></html>`;
}
