# -*- coding: utf-8 -*-
"""
THE FACES, HOSTED BY THE PACKAGE — no Google Fonts, no CDN, no network at
run time. The studio has to work on a laptop with the internet off.

Nothing here is copied by name or by guess: every file is IDENTIFIED by
reading its own tables — family, weight, and the exact codepoints it
carries — so the `unicode-range` in the stylesheet is the range the file
actually covers rather than a block copied off a website. A wrong range is
the worst kind of font bug: the browser downloads the file and then refuses
to use it, and the text silently falls back.

The licence is read out of the binaries too (name ID 14), not asserted.

Run: python packages/zaki-ui/scripts/build-fonts.py
"""
import glob
import io
import os
import shutil

from fontTools.ttLib import TTFont

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(PKG))
MEDIA = os.path.join(REPO, '.next', 'dev', 'static', 'media')
OUT = os.path.join(PKG, 'fonts')

# The four weights the product declares, and no fifth.
WANT_FAMILY = 'IBM Plex Sans Arabic'
# FOUR WEIGHTS, to match operations exactly.
#
# The product declares 400/500/600/700 and uses all four — `font-medium` and
# `font-bold` are not decoration on a dashboard, they are how a total is
# told apart from the row above it. Shipping two would have left the studio
# synthesising the other two, and a synthesised bold is visibly not a drawn
# one: the strokes thicken evenly instead of where a designer put the
# weight.
WANT_WEIGHTS = {400: 'regular', 500: 'medium', 600: 'semibold', 700: 'bold'}

# Arabic block starts here; anything with these is the Arabic cut.
ARABIC = range(0x0600, 0x0700)


def ranges(codepoints):
    """Contiguous runs, as CSS writes them."""
    out = []
    start = prev = None
    for cp in sorted(codepoints):
        if start is None:
            start = prev = cp
            continue
        if cp == prev + 1:
            prev = cp
            continue
        out.append((start, prev))
        start = prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def css_range(runs):
    parts = []
    for a, b in runs:
        parts.append('U+%04X' % a if a == b else 'U+%04X-%04X' % (a, b))
    return ', '.join(parts)


def describe(path):
    f = TTFont(path, lazy=True)
    names = {}
    for rec in f['name'].names:
        if rec.nameID in (1, 14, 16) and rec.nameID not in names:
            try:
                names[rec.nameID] = str(rec)
            except Exception:  # noqa: BLE001
                pass
    cps = set()
    for table in f['cmap'].tables:
        cps.update(table.cmap.keys())
    weight = f['OS/2'].usWeightClass
    f.close()
    return {
        'path': path,
        'family': names.get(16) or names.get(1),
        'licenceUrl': names.get(14),
        'weight': weight,
        'codepoints': cps,
        'arabic': any(cp in ARABIC for cp in cps),
        'bytes': os.path.getsize(path),
    }


found = [describe(p) for p in sorted(glob.glob(os.path.join(MEDIA, '*.woff2')))]
plex = [f for f in found if (f['family'] or '').startswith(WANT_FAMILY)]

os.makedirs(OUT, exist_ok=True)
for old in glob.glob(os.path.join(OUT, '*.woff2')):
    os.remove(old)

faces = []
for weight, label in sorted(WANT_WEIGHTS.items()):
    cuts = [f for f in plex if f['weight'] == weight]
    if not cuts:
        raise SystemExit('no file for weight %d — was the app built with this weight?' % weight)
    # The two cuts the owner asked for: the Arabic one, and the Latin one —
    # which is the largest of the rest. The tiny fragments next/font emits
    # (a 1 KB file of six glyphs) are left out on purpose: they cost a
    # request each to cover punctuation the Latin cut already carries.
    arabic = max((f for f in cuts if f['arabic']), key=lambda f: len(f['codepoints']), default=None)
    latin = max((f for f in cuts if not f['arabic']), key=lambda f: len(f['codepoints']), default=None)
    for subset, src in (('arabic', arabic), ('latin', latin)):
        if src is None:
            print('  ! no %s cut for weight %d' % (subset, weight))
            continue
        name = 'ibm-plex-sans-arabic-%s-%s.woff2' % (weight, subset)
        shutil.copyfile(src['path'], os.path.join(OUT, name))
        faces.append({
            'file': name,
            'weight': weight,
            'label': label,
            'subset': subset,
            'bytes': src['bytes'],
            'glyphs': len(src['codepoints']),
            'range': css_range(ranges(src['codepoints'])),
            'licenceUrl': src['licenceUrl'],
        })

lic = sorted({f['licenceUrl'] for f in faces if f['licenceUrl']})

css = ["""/*
 * zaki-ui fonts — IBM Plex Sans Arabic, hosted here.
 *
 * GENERATED by packages/zaki-ui/scripts/build-fonts.py. Every file was
 * identified by reading its own tables, and each `unicode-range` below is
 * the set of codepoints that file ACTUALLY carries — not a block copied
 * from a website. A wrong range is the worst font bug there is: the browser
 * fetches the file, refuses to use it, and the text falls back silently.
 *
 * `font-display: swap` matches what the product does today: text is
 * readable immediately in the fallback and reflows once, rather than
 * leaving a warehouse screen blank while a font downloads.
 *
 * Licence, read out of the binaries: %s
 */""" % (', '.join(lic) or '(none declared in the files)')]

for f in faces:
    css.append("""@font-face {
  font-family: 'IBM Plex Sans Arabic';
  font-style: normal;
  font-weight: %d;
  font-display: swap;
  src: url('./fonts/%s') format('woff2');
  unicode-range: %s;
}""" % (f['weight'], f['file'], f['range']))

io.open(os.path.join(PKG, 'fonts.css'), 'w', encoding='utf-8', newline='\n').write('\n\n'.join(css) + '\n')

io.open(os.path.join(OUT, 'LICENSE.md'), 'w', encoding='utf-8', newline='\n').write(
    '# الخطوط في هذه الحزمة\n\n'
    '**IBM Plex Sans Arabic** — الرخصةُ كما تُعلنها ملفّاتُ الخطّ نفسُها في\n'
    'حقل `name ID 14`:\n\n'
    + ''.join('- %s\n' % u for u in lic)
    + '\nوهي **SIL Open Font License 1.1**، وتسمح بإعادة التوزيع ضمن هذه الحزمة.\n\n'
    '## ما ينقص قبل التوزيع خارج هذا الجهاز\n\n'
    'الرخصةُ تشترط أن **يُرفَق نصُّها الكامل** مع الملفّات المُوزَّعة، ولا نسخةَ\n'
    'منه على هذا الجهاز — فلم أكتبه من الذاكرة. ضَعْ ملفَّ `OFL.txt` من مصدر\n'
    'الخطّ هنا قبل أن تُشحن الحزمة إلى أيّ جهازٍ آخر.\n\n'
    'ولا يجوز بيعُ الخطوط وحدَها، ولا استعمالُ اسم المُصدِر للترويج — وكلاهما\n'
    'لا يعنينا هنا، لكنّهما شرطان في الرخصة.\n'
)

total = sum(f['bytes'] for f in faces)
print('fonts.css + %d files (%.0f KB)' % (len(faces), total / 1024))
for f in faces:
    print('  %-44s %-9s %5.0f KB  %5d glyphs' % (f['file'], f['subset'], f['bytes'] / 1024, f['glyphs']))
print('licence (from the binaries):', ', '.join(lic) or '(none)')
